name = "comfyui-deploy"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
dist = "dist"

[site]
bucket = "./public"

[env.production]
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = 'STORAGE'
bucket_name = 'comfyui-deploy' 