name = "comfyui-deploy-figma"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bash web/build.sh"
cwd = "/"
dist = "web/.next"

[site]
bucket = "./public"

[env.production]
vars = { ENVIRONMENT = "production" }

# R2 配置
[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'comfyui-deploy'

# 环境变量
[vars]
NODE_ENV = "production"

# 使用已配置的环境变量
# SPACES_ENDPOINT
# SPACES_ENDPOINT_CDN
# SPACES_BUCKET
# SPACES_KEY
# SPACES_SECRET
# DATABASE_URL (Neon)

# 数据库配置
[[ d1_databases ]]
binding = "DB"
database_name = "comfyui-deploy"
database_id = "xxx" 